name: Say Hello World
on:
  issues:
    types:
      - opened

jobs:
  run-bot-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: probot/example-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
